namespace Spritey.ImageProcessing.CompositeMapping
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;

    /// <summary>
    /// Statistics gathered by a canvas.
    /// </summary>
    internal class CanvasStats : ICanvasStats
    {
        /// <summary>
        /// Gets or sets number of times an attempt was made to add an image to the canvas used by the mapper.
        /// </summary>
        public int RectangleAddAttempts { get; set; }

        /// <summary>
        /// Gets or sets number of cells generated by the canvas.
        /// </summary>
        public int NbrCellsGenerated { get; set; }

        /// <summary>
        /// Gets or sets see ICanvasStats
        /// </summary>
        public int LowestFreeHeightDeficit { get; set; }
    }
}
